hidden_layer_size: 3
node_add_prob: 0.2
conn_add_prob: 0.4
mutate_add_connection_weights:
  # the sum of the probability shall be 1
  - 0.6 #add a ih connection
  - 0.1 #add a hh connection
  - 0.28 #add a ho connection
  - 0.02 #random change all the weights of this node
# initial connection: full/none/random/layer
initial_connection: none

